class Movie {
  final String title;
  final String description;
  final String imageUrl;
  final double rating;
  final String trailerUrl;
  final String duration;
  final String releaseYear;
  final String director;
  final String actors;
  final List<String> genres;
  Movie({
    required this.title,
    required this.description,
    required this.imageUrl,
    required this.rating,
    required this.trailerUrl,
    required this.duration,
    required this.releaseYear,
    required this.director,
    required this.actors,
    required this.genres,
  });
}

List<Movie> allMovies = [
  Movie(
    title: "Breaking Bad",
    description: "Seorang guru kimia yang didiagnosis menderita kanker beralih ke pembuatan metamfetamin demi masa depan keluarganya.",
    imageUrl: "assets/images/BreakinBad.jpg",
    rating: 9.5,
    trailerUrl: "https://www.youtube.com/watch?v=HhesaQXLuRY",
    duration: "45m / Eps",
    releaseYear: "2008",
    director: "Vince Gilligan",
    actors: "Bryan Cranston, Aaron Paul",
    genres: ["Action", "Crime", "Drama"],
  ),
  Movie(
    title: "12 Angry Men",
    description: "Seorang juri dalam pengadilan kasus pembunuhan berusaha mencegah ketidakadilan dengan meyakinkan 11 juri lainnya untuk mempertimbangkan kembali bukti-bukti yang ada secara objektif.",
    imageUrl: "assets/images/12AM.jpg",
    rating: 9.0,
    trailerUrl: "https://www.youtube.com/watch?v=_13J_9B5jEk",
    duration: "1j 36m",
    releaseYear: "1957",
    director: "Sidney Lumet",
    actors: "Henry Fonda, Lee J. Cobb, Martin Balsam",
    genres: ["Drama", "Crime", "Hukum"],
  ),
  Movie(
    title: "Better Call Saul",
    description: "Prekuel dari Breaking Bad yang mengisahkan perjalanan Jimmy McGill, seorang pengacara kecil yang berjuang keras sebelum akhirnya bertransformasi menjadi pengacara kriminal eksentrik bernama Saul Goodman.",
    imageUrl: "assets/images/BCS.jpg",
    rating: 9.0,
    trailerUrl: "https://www.youtube.com/watch?v=HN4oydykJFc",
    duration: "45m / Eps",
    releaseYear: "2015",
    director: "Vince Gilligan, Peter Gould",
    actors: "Bob Odenkirk, Rhea Seehorn, Jonathan Banks",
    genres: ["Crime", "Drama", "Komedi Gelap"],
  ),
  Movie(
    title: "Agak Laen",
    description: "Empat sekawan penjaga rumah hantu di pasar malam mencari cara baru menakuti pengunjung agar tidak bangkrut.",
    imageUrl: "assets/images/AgakLaen.jpg", 
    rating: 8.8,
    trailerUrl: "https://www.youtube.com/watch?v=kR02P6E0B8Y",
    duration: "1j 59m",
    releaseYear: "2024",
    director: "Muhadkly Acho",
    actors: "Bene Dion, Boris Bokir, Indra Jegel",
    genres: ["Komedi", "Horor"],
  ),
  Movie(
    title: "Grave of the Fireflies",
    description: "Serangan bom pesawat Amerika Serikat menghancurkan kota tersebut. Seita (remaja laki-laki) dan Setsuko (adik perempuannya yang masih kecil) kehilangan ibu mereka yang tewas akibat luka bakar parah saat pengeboman.",
    imageUrl: "assets/images/FireFlies.jpeg",
    rating: 8.2,
    trailerUrl: "https://youtu.be/lhlh7JVcTt8",
    duration: "1j 29m",
    releaseYear: "1988",
    director: "Isao Takahata",
    actors: "Tsutomu Tatsumi, Ayano Shiraishi",
    genres: ["Animasi", "Drama", "Perang"],
  ),
  Movie(
    title: "500 Days of Summer",
    description: "Kisah komedi romantis non-linear tentang seorang pria yang jatuh cinta pada pandangan pertama dengan seorang wanita yang sama sekali tidak percaya pada cinta sejati.",
    imageUrl: "assets/images/500days.jpg",
    rating: 7.7,
    trailerUrl: "https://youtu.be/PsD0NpFSADM",
    duration: "1j 35m",
    releaseYear: "2009",
    director: "Marc Webb",
    actors: "Joseph Gordon-Levitt, Zooey Deschanel",
    genres: ["Komedi", "Romantis", "Slice of Life"],
  ),
  Movie(
    title: "Avengers: Endgame",
    description: "Setelah jentikan jari Thanos yang melenyapkan separuh populasi semesta, sisa-sisa Avengers berkumpul sekali lagi untuk mengembalikan keseimbangan alam semesta.",
    imageUrl: "assets/images/Avenger.jpg",
    rating: 8.4,
    trailerUrl: "https://www.youtube.com/watch?v=TcMBFSGVi1c",
    duration: "3j 1m",
    releaseYear: "2019",
    director: "Anthony & Joe Russo",
    actors: "Robert Downey Jr., Chris Evans, Scarlett Johansson",
    genres: ["Action", "Sci-Fi", "Petualangan"],
  ),
  Movie(
    title: "Miracle In Cell No. 7",
    description: "Seorang ayah dengan keterbelakangan mental yang dituduh secara tidak sah atas kasus pembunuhan. Ia membangun persahabatan dengan narapidana lain untuk bisa bertemu putrinya.",
    imageUrl: "assets/images/Miracle.jpg",
    rating: 8.6,
    trailerUrl: "https://youtu.be/h9MGZFy-gog",
    duration: "2j 7m",
    releaseYear: "2013",
    director: "Lee Hwan-kyung",
    actors: "Ryu Seung-ryong, Kal So-won, Park Shin-hye",
    genres: ["Drama", "Komedi", "Keluarga"],
  ),
  Movie(
    title: "You Are the Apple of My Eye",
    description: "Sekelompok sahabat sekolah yang menyukai siswi teladan bernama Shen Chia-yi. Fokus utamanya adalah hubungan antara si pembuat onar, Ko-teng, dengan Shen Chia-yi.",
    imageUrl: "assets/images/Apple.jpg",
    rating: 8.5,
    trailerUrl: "https://youtu.be/gQylx2S9yrM",
    duration: "1j 49m",
    releaseYear: "2011",
    director: "Giddens Ko",
    actors: "Kai Ko, Michelle Chen",
    genres: ["Romantis", "Komedi", "Slice of Life"],
  ),
  Movie(
    title: "The Walking Dead",
    description: "Deputi sheriff Rick Grimes memimpin sekelompok penyintas di dunia yang telah dikuasai zombie, menghadapi ancaman yang lebih besar dari sesama manusia.",
    imageUrl: "assets/images/TWD.jpg",
    rating: 8.7,
    trailerUrl: "https://youtu.be/cu2ApTImBKc",
    duration: "44m / Eps",
    releaseYear: "2010",
    director: "Frank Darabont",
    actors: "Andrew Lincoln, Norman Reedus",
    genres: ["Horor", "Thriller", "Drama"],
  ),
  Movie(
    title: "One Piece",
    description: "Petualangan Monkey D. Luffy bersama krunya, Bajak Laut Topi Jerami, mengarungi lautan untuk menemukan harta karun legendaris One Piece dan menjadi Raja Bajak Laut.",
    imageUrl: "assets/images/OP.jpg",
    rating: 9.9,
    trailerUrl: "https://youtu.be/lgAwlnGLTUg",
    duration: "24m / Eps",
    releaseYear: "1999",
    director: "Eiichiro Oda (Creator)",
    actors: "Mayumi Tanaka, Kazuya Nakai",
    genres: ["Animasi", "Petualangan", "Action", "Komedi"],
  ),
];
List<Movie> favoriteMovies = [];